# Generated by Django 5.0.6 on 2024-05-24 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.TextField(max_length=255, null=True)),
                ("email", models.TextField(max_length=255, null=True)),
                ("telefone", models.TextField(max_length=255, null=True)),
                ("endereco", models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Estoque",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("quantidade", models.IntegerField(null=True)),
                ("localizacao", models.TextField(max_length=255, null=True)),
                ("data_entrada", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.TextField(max_length=255)),
                ("cnpj_cpf", models.TextField(max_length=15)),
                ("contato", models.TextField(max_length=100, null=True)),
                ("endereco", models.TextField(max_length=255, null=True)),
                ("classificacao_preco", models.TextField(max_length=45, null=True)),
                ("classificacao_tempo", models.TextField(max_length=45, null=True)),
                ("classificacao_qualidade", models.TextField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Registro_Historico",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("descricao", models.TextField(max_length=255, null=True)),
                ("tipo", models.TextField(max_length=255, null=True)),
                ("detalhes", models.TextField(max_length=255, null=True)),
                ("data_registro", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.TextField(max_length=255)),
                ("idade", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("descricao", models.TextField(max_length=255, null=True)),
                ("tipo", models.TextField(max_length=255, null=True)),
                ("data_alerta", models.DateField(auto_now_add=True)),
                (
                    "estoque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_lojaferragens.estoque",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("data_compra", models.DateField(auto_now_add=True)),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_lojaferragens.fornecedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.TextField(max_length=255, null=True)),
                ("descricao", models.TextField(max_length=255, null=True)),
                (
                    "preco_venda",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "custo",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("imagem", models.TextField(max_length=255, null=True)),
                ("manual_instrucao", models.TextField(max_length=255, null=True)),
                ("classificacao", models.TextField(max_length=255, null=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_lojaferragens.categoria",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_lojaferragens.fornecedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Itens_Compra",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("quantidade", models.IntegerField(null=True)),
                (
                    "preco_lote",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("unidade_medida", models.TextField(max_length=255, null=True)),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_lojaferragens.compra",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_lojaferragens.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fracionamento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("quantidade_fracionada", models.IntegerField(null=True)),
                ("data_fracionamento", models.DateField(auto_now_add=True)),
                ("fracionamentocol", models.TextField(max_length=255, null=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_lojaferragens.produto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="estoque",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app_lojaferragens.produto",
            ),
        ),
        migrations.CreateModel(
            name="Sub_Categoria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.TextField(max_length=255)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_lojaferragens.categoria",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="produto",
            name="sub_categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app_lojaferragens.sub_categoria",
            ),
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("data_venda", models.DateField(auto_now_add=True)),
                ("tipo", models.TextField(max_length=255, null=True)),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_lojaferragens.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Itens_Venda",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("quantidade_vendida", models.IntegerField(null=True)),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "total_item_venda",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_lojaferragens.produto",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_lojaferragens.venda",
                    ),
                ),
            ],
        ),
        migrations.RunSQL(sql="INSERT INTO `app_lojaferragens`.`app_lojaferragens_categoria` (`nome`) VALUES ('teste_categoria');"),
        migrations.RunSQL(sql="INSERT INTO `app_lojaferragens`.`app_lojaferragens_fornecedor`" +
                          " (`nome`, `cnpj_cpf`, `contato`, `endereco`, `classificacao_preco`, `classificacao_tempo`, `classificacao_qualidade`) " +
                          " VALUES ( 'teste fornecedor','1234567890','1234567894', 'rua sem nome, s/n bairro esquecido', 'não sei', 'não sei', 'não sei');"), 
        migrations.RunSQL(sql="INSERT INTO `app_lojaferragens`.`app_lojaferragens_sub_categoria` (`nome`, `categoria_id`) VALUES " +
                          " ( 'teste sub_categoria', 1);"),
        migrations.RunSQL(sql="INSERT INTO `app_lojaferragens`.`app_lojaferragens_produto` ( `nome`, `descricao`, `preco_venda`, `custo`, " +
                          " `imagem`, `manual_instrucao`, `classificacao`, `categoria_id`, `fornecedor_id`, `sub_categoria_id`) VALUES " +
                          "( 'produto de teste', 'produto de teste', 500.00, 120.00, 'Não sei', 'Não sei', 'Não sei', 1, 1, 1);"),
        migrations.RunSQL(sql="INSERT INTO `app_lojaferragens`.`app_lojaferragens_produto` ( `nome`, `descricao`, `preco_venda`, `custo`, " +
                          " `imagem`, `manual_instrucao`, `classificacao`, `categoria_id`, `fornecedor_id`, `sub_categoria_id`) VALUES " +
                          "( 'produto de teste 2', 'produto de teste 2', 400.00, 20.00, 'Não sei', 'Não sei', 'Não sei', 1, 1, 1);"),
    ]
